### ISSUE TITLE
关闭 结界票满清理还是会触发结界突破问题

### ISSUE THREAD

**Issue by CokdeK** [YaKun9/YYS-AutoHelpMe#1]
取消勾选结界票满清理还是会跳转到结界突破
且30次清完后跳转困28失败 一直循环结界票为0-结界突破-结界票为0
使用的是打包好的懒人版

**Comment by YaKun9** [comment]
应该是上次逻辑没写完，有时间改一下

**Comment by Ma-Gui-Jun** [comment]
> 取消勾选结界票满清理还是会跳转到结界突破 且30次清完后跳转困28失败 一直循环结界票为0-结界突破-结界票为0 使用的是打包好的懒人版

**Comment by Ma-Gui-Jun** [comment]
哪里来的打包好的啊，我不知道在哪里下载

**Comment by YaKun9** [comment]
> 哪里来的打包好的啊，我不知道在哪里下载

https://github.com/YaKun9/YYS-AutoHelpMe/releases

**Comment by vahallaaa** [comment]
> 取消勾选结界票满清理还是会跳转到结界突破 且30次清完后跳转困28失败 一直循环结界票为0-结界突破-结界票为0 使用的是打包好的懒人版

你好,想问下,还在使用吗,有被黑吗,win裸奔吗

**Comment by xiaofeng221** [comment]
大佬真牛  点赞加星

**Comment by xiaofeng221** [comment]
如果可以适配更小的窗口就更好了

**Comment by renvys** [comment]
请问mumu模拟器点击标题栏锁定是什么意思，我用mumu模拟器开始后没有反应

**Comment by YaKun9** [comment]
> 请问mumu模拟器点击标题栏锁定是什么意思，我用mumu模拟器开始后没有反应

点击mumu模拟器窗口获取句柄，而非游戏画面。
游戏画面也行，只是会频繁获取鼠标。

用管理员身份运行。有空了我补充一下文档

**Comment by YaKun9** [comment]
> 如果可以适配更小的窗口就更好了

重新截一套图就可以了

**Comment by xiaofeng221** [comment]
**在分辨率2560x1440打开软件   软件界面显示不完整，无法缩放调整**

**Comment by YaKun9** [comment]
> **在分辨率2560x1440打开软件 软件界面显示不完整，无法缩放调整**

挺没道理的,我自己的电脑也是 2560*1440，有时间我设置一下缩放模式
