### ISSUE TITLE
请教一下......

### ISSUE THREAD

**Issue by li9296** [YaKun9/YYS-AutoHelpMe#10]
大佬，晚上好，我琢磨了一天      还是不太不明白怎么将大佬的代码打包成程序
大佬可以指明一下方向吗......
比如去哪里有教程，去哪里学习之类......
感激不尽！

**Comment by YaKun9** [comment]
啊? 这要啥教程？vs打开之后，构建项目，然后去项目bin目录下debug/release文件夹下找文件

**Comment by YaKun9** [comment]
li9296
如果是想要打包成安装程序,可以参考  winform程序打包安装程序


这里有一个参考博文:
https://blog.csdn.net/xfy18317776108/article/details/122343091

**Comment by li9296** [comment]
好  我去试试看，感谢大佬回复
（太萌新了  很多不懂  都是碰到问题去搜，一个一个解决这样......）

**Comment by YaKun9** [comment]
> 好 我去试试看，感谢大佬回复 （太萌新了 很多不懂 都是碰到问题去搜，一个一个解决这样......）

正常正常，这程序我就是一点点搜写出来的。配合ChatGPT写更好

**Comment by li9296** [comment]
大佬牛啊！

**Comment by li9296** [comment]
大佬刚刚讲的vs   是你写的devexpress吗

**Comment by YaKun9** [comment]
> 大佬刚刚讲的vs 是你写的devexpress吗

visual studio ， 技术栈是 winform。建议先学习一下相关基础知识

**Comment by li9296** [comment]
好的，谢谢大佬，去学习基础知识了

**Comment by li9296** [comment]
大佬好，想反馈一个问题，脚本在探索运行中，当突破票满30后，会一直重复点击突破票数，
不能点下面横栏的突破

**Comment by hh233330** [comment]
活动爬塔怎么添加？

**Comment by YaKun9** [comment]
图片识别问题，现在这个功能它不好用，你需要再优化一下。

**Comment by YaKun9** [comment]
> 大佬好，想反馈一个问题，脚本在探索运行中，当突破票满30后，会一直重复点击突破票数， 不能点下面横栏的突破

图片识别问题，现在这个功能它不好用，你需要再优化一下。

**Comment by YaKun9** [comment]
> 活动爬塔怎么添加？

自行修改活动代码里的逻辑

**Comment by YaKun9** [comment]
> 活动爬塔怎么添加？

亦或替换 `/Resource/MNQImages/挑战_活动.png`文件

**Comment by 861932534** [comment]
大佬devexpress破解软件有波？

**Comment by YaKun9** [comment]
> 大佬devexpress破解软件有波？
开发者论坛找一下
https://www.dxper.net/
