### ISSUE TITLE
这个需要虚拟机或者沙盒之类的吗

### ISSUE THREAD

**Issue by vahallaaa** [YaKun9/YYS-AutoHelpMe#2]
还是直接win裸奔就可以,还有想问下大佬你自己用的频率,刷的时间,还有被黑的情况 十分感谢

**Comment by YaKun9** [comment]
不需要虚拟机,因为我一直在模拟器上使用。使用情况，大号刷了十万体力左右，之前还刷了绘卷前百，从最早开发至今几个月没黑过

**Comment by YaKun9** [comment]
但是因人而异，个人体质不同，不保证一定不黑

**Comment by YaKun9** [comment]
今天刷了两个小时左右（阳了在发烧，起不来），没问题
