### ISSUE TITLE
大佬有加偏移和延迟吗

### ISSUE THREAD

**Issue by vahallaaa** [YaKun9/YYS-AutoHelpMe#3]
使用了一下，体感还可以，但是感觉，点击战斗开始的速度好快，不知道有没有设置随机偏移和延迟

**Comment by YaKun9** [comment]
有的，嫌快可以自行在[WinHelper](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/WinHelper.cs)类中调整,分别是 `Click()`方法和`RandomDelay()`方法
