### ISSUE TITLE
秘闻不能使用

### ISSUE THREAD

**Issue by anihao** [YaKun9/YYS-AutoHelpMe#5]
秘闻开启后没反应，只有战斗完帮点两下屏幕

**Comment by YaKun9** [comment]
哪一个秘闻？

可以自己先截图一个秘闻的挑战按钮，替换掉 `Resource\MNQImages\挑战_秘闻.png` 文件

**Comment by anihao** [comment]
好的，我试试看

**Comment by YaKun9** [comment]
![挑战_秘闻](https://github.com/YaKun9/YYS-AutoHelpMe/assets/131952790/34409eac-4fdd-438c-8120-1c733b3f7060)

参考一下我这个

**Comment by anihao** [comment]
![QQ截图20230526142055](https://github.com/YaKun9/YYS-AutoHelpMe/assets/111543417/972de563-80a9-449c-9b82-8f856de57d76)

**Comment by anihao** [comment]
png文件是一致的，但没有触发自动挑战，御魂、探索都正常

**Comment by YaKun9** [comment]
可以了，已更新

https://github.com/YaKun9/YYS-AutoHelpMe/releases/tag/v1.0.2
