### ISSUE TITLE
from qq邮箱

### ISSUE THREAD

**Issue by BaryRR** [YaKun9/YYS-AutoHelpMe#8]
收到大佬的回复,具体情况是使用mumu模拟器双开挖土,操作司机的脚本不会在准备界面点击挑战按钮窗口
使用雷电9就可以正常使用
操作系统版本Windows 10 专业版 21H2
处理器 AMD5600
显卡 6800xt
显示器分辨率 3440*1440  100%缩放

**Comment by LiuDanK** [comment]
好的,有时间我测试一下，用mumu以来我还没组过队

**Comment by BaryRR** [comment]
> 好的,有时间我测试一下，用mumu以来我还没组过队

好的 麻烦大佬了,话说我本身是java的后端开发,可以透露一下这个项目的实现思想是什么嘛,这两天使用下来我也有些优化的想法想自己尝试一下,但是我又没学过C#还建议尝试吗

**Comment by LiuDanK** [comment]
> > 好的,有时间我测试一下，用mumu以来我还没组过队
> 
> 好的 麻烦大佬了,话说我本身是java的后端开发,可以透露一下这个项目的实现思想是什么嘛,这两天使用下来我也有些优化的想法想自己尝试一下,但是我又没学过C#还建议尝试吗

大致思路就是截取游戏里面的局部图片，比如挑战按钮，然后截屏游戏窗口，通过OpenCV查找小图（比如挑战按钮），如果查找到了就进行点击操作。可以看下这个方法的实现,199行的`Demo()`[点击跳转](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/Function/Function.Other.cs)

Java和C#差不太多，上手还是比较容易的。百度百度就差不多了

**Comment by BaryRR** [comment]
> > > 好的,有时间我测试一下，用mumu以来我还没组过队
> > 
> > 
> > 好的 麻烦大佬了,话说我本身是java的后端开发,可以透露一下这个项目的实现思想是什么嘛,这两天使用下来我也有些优化的想法想自己尝试一下,但是我又没学过C#还建议尝试吗
> 
> 大致思路就是截取游戏里面的局部图片，比如挑战按钮，然后截屏游戏窗口，通过OpenCV查找小图（比如挑战按钮），如果查找到了就进行点击操作。可以看下这个方法的实现,199行的`Demo()`[点击跳转](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/Function/Function.Other.cs)
> 
> Java和C#差不太多，上手还是比较容易的。百度百度就差不多了

好的 多谢大佬指点，今晚把环境搭建起来了，核心逻辑确实基本能看懂，之后得空了我尝试下加入我的想法

**Comment by YaKun9** [comment]
> > > > 好的,有时间我测试一下，用mumu以来我还没组过队
> > > 
> > > 
> > > 好的 麻烦大佬了,话说我本身是java的后端开发,可以透露一下这个项目的实现思想是什么嘛,这两天使用下来我也有些优化的想法想自己尝试一下,但是我又没学过C#还建议尝试吗
> > 
> > 
> > 大致思路就是截取游戏里面的局部图片，比如挑战按钮，然后截屏游戏窗口，通过OpenCV查找小图（比如挑战按钮），如果查找到了就进行点击操作。可以看下这个方法的实现,199行的`Demo()`[点击跳转](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/Function/Function.Other.cs)
> > Java和C#差不太多，上手还是比较容易的。百度百度就差不多了
> 
> 好的 多谢大佬指点，今晚把环境搭建起来了，核心逻辑确实基本能看懂，之后得空了我尝试下加入我的想法

嗯嗯，届时欢迎提交pull request，加油！！！（最近懒得玩，也懒得写了）

**Comment by BaryRR** [comment]
> > > > > 好的,有时间我测试一下，用mumu以来我还没组过队
> > > > 
> > > > 
> > > > 好的 麻烦大佬了,话说我本身是java的后端开发,可以透露一下这个项目的实现思想是什么嘛,这两天使用下来我也有些优化的想法想自己尝试一下,但是我又没学过C#还建议尝试吗
> > > 
> > > 
> > > 大致思路就是截取游戏里面的局部图片，比如挑战按钮，然后截屏游戏窗口，通过OpenCV查找小图（比如挑战按钮），如果查找到了就进行点击操作。可以看下这个方法的实现,199行的`Demo()`[点击跳转](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/Function/Function.Other.cs)
> > > Java和C#差不太多，上手还是比较容易的。百度百度就差不多了
> > 
> > 
> > 好的 多谢大佬指点，今晚把环境搭建起来了，核心逻辑确实基本能看懂，之后得空了我尝试下加入我的想法
> 
> 嗯嗯，届时欢迎提交pull request，加油！！！（最近懒得玩，也懒得写了）

昨天游戏更新了,我尝试把契灵探查功能和017的50自选加进去了,现在想实现自动捕捉契灵的功能,中间有一个步骤要求发指令控制鼠标在屏幕画条折现连接三个点,这个控制鼠标绘图的功能我该用什么关键字百度呢

**Comment by YaKun9** [comment]
> 

win32API实现鼠标点击
win32API实现鼠标移动  `MOUSE_MOVE` ，对应的具体事件名忘记了。

我使用的win32api的包是 `PInvoke.NET`

**Comment by YaKun9** [comment]
> > > > > > 好的,有时间我测试一下，用mumu以来我还没组过队
> > > > > 
> > > > > 
> > > > > 好的 麻烦大佬了,话说我本身是java的后端开发,可以透露一下这个项目的实现思想是什么嘛,这两天使用下来我也有些优化的想法想自己尝试一下,但是我又没学过C#还建议尝试吗
> > > > 
> > > > 
> > > > 大致思路就是截取游戏里面的局部图片，比如挑战按钮，然后截屏游戏窗口，通过OpenCV查找小图（比如挑战按钮），如果查找到了就进行点击操作。可以看下这个方法的实现,199行的`Demo()`[点击跳转](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/Function/Function.Other.cs)
> > > > Java和C#差不太多，上手还是比较容易的。百度百度就差不多了
> > > 
> > > 
> > > 好的 多谢大佬指点，今晚把环境搭建起来了，核心逻辑确实基本能看懂，之后得空了我尝试下加入我的想法
> > 
> > 
> > 嗯嗯，届时欢迎提交pull request，加油！！！（最近懒得玩，也懒得写了）
> 
> 昨天游戏更新了,我尝试把契灵探查功能和017的50自选加进去了,现在想实现自动捕捉契灵的功能,中间有一个步骤要求发指令控制鼠标在屏幕画条折现连接三个点,这个控制鼠标绘图的功能我该用什么关键字百度呢

win32API实现鼠标点击
win32API实现鼠标移动 MOUSE_MOVE ，对应的具体事件名忘记了。

我使用的win32api的包是 PInvoke.NET

**Comment by YaKun9** [comment]
> > > > > > > 好的,有时间我测试一下，用mumu以来我还没组过队
> > > > > > 
> > > > > > 
> > > > > > 好的 麻烦大佬了,话说我本身是java的后端开发,可以透露一下这个项目的实现思想是什么嘛,这两天使用下来我也有些优化的想法想自己尝试一下,但是我又没学过C#还建议尝试吗
> > > > > 
> > > > > 
> > > > > 大致思路就是截取游戏里面的局部图片，比如挑战按钮，然后截屏游戏窗口，通过OpenCV查找小图（比如挑战按钮），如果查找到了就进行点击操作。可以看下这个方法的实现,199行的`Demo()`[点击跳转](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/Function/Function.Other.cs)
> > > > > Java和C#差不太多，上手还是比较容易的。百度百度就差不多了
> > > > 
> > > > 
> > > > 好的 多谢大佬指点，今晚把环境搭建起来了，核心逻辑确实基本能看懂，之后得空了我尝试下加入我的想法
> > > 
> > > 
> > > 嗯嗯，届时欢迎提交pull request，加油！！！（最近懒得玩，也懒得写了）
> > 
> > 
> > 昨天游戏更新了,我尝试把契灵探查功能和017的50自选加进去了,现在想实现自动捕捉契灵的功能,中间有一个步骤要求发指令控制鼠标在屏幕画条折现连接三个点,这个控制鼠标绘图的功能我该用什么关键字百度呢
> 
> win32API实现鼠标点击 win32API实现鼠标移动 MOUSE_MOVE ，对应的具体事件名忘记了。
> 
> 我使用的win32api的包是 PInvoke.NET

回头搞好了合并出来
![162B2D37](https://github.com/YaKun9/YYS-AutoHelpMe/assets/131952790/508253d3-0118-4bcd-9648-9962d6277e5f)
我已经好多天没上线了
![162B68F7](https://github.com/YaKun9/YYS-AutoHelpMe/assets/131952790/3bdb2800-7f54-4e73-9c72-553e5ac4ea7d)

**Comment by BaryRR** [comment]
> > > > > > > > 好的,有时间我测试一下，用mumu以来我还没组过队
> > > > > > > 
> > > > > > > 
> > > > > > > 好的 麻烦大佬了,话说我本身是java的后端开发,可以透露一下这个项目的实现思想是什么嘛,这两天使用下来我也有些优化的想法想自己尝试一下,但是我又没学过C#还建议尝试吗
> > > > > > 
> > > > > > 
> > > > > > 大致思路就是截取游戏里面的局部图片，比如挑战按钮，然后截屏游戏窗口，通过OpenCV查找小图（比如挑战按钮），如果查找到了就进行点击操作。可以看下这个方法的实现,199行的`Demo()`[点击跳转](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/Function/Function.Other.cs)
> > > > > > Java和C#差不太多，上手还是比较容易的。百度百度就差不多了
> > > > > 
> > > > > 
> > > > > 好的 多谢大佬指点，今晚把环境搭建起来了，核心逻辑确实基本能看懂，之后得空了我尝试下加入我的想法
> > > > 
> > > > 
> > > > 嗯嗯，届时欢迎提交pull request，加油！！！（最近懒得玩，也懒得写了）
> > > 
> > > 
> > > 昨天游戏更新了,我尝试把契灵探查功能和017的50自选加进去了,现在想实现自动捕捉契灵的功能,中间有一个步骤要求发指令控制鼠标在屏幕画条折现连接三个点,这个控制鼠标绘图的功能我该用什么关键字百度呢
> > 
> > 
> > win32API实现鼠标点击 win32API实现鼠标移动 MOUSE_MOVE ，对应的具体事件名忘记了。
> > 我使用的win32api的包是 PInvoke.NET
> 
> 回头搞好了合并出来 ![162B2D37](https://user-images.githubusercontent.com/131952790/244636760-508253d3-0118-4bcd-9648-9962d6277e5f.png) 我已经好多天没上线了 ![162B68F7](https://user-images.githubusercontent.com/131952790/244636814-3bdb2800-7f54-4e73-9c72-553e5ac4ea7d.png)



> > > > > > > > 好的,有时间我测试一下，用mumu以来我还没组过队
> > > > > > > 
> > > > > > > 
> > > > > > > 好的 麻烦大佬了,话说我本身是java的后端开发,可以透露一下这个项目的实现思想是什么嘛,这两天使用下来我也有些优化的想法想自己尝试一下,但是我又没学过C#还建议尝试吗
> > > > > > 
> > > > > > 
> > > > > > 大致思路就是截取游戏里面的局部图片，比如挑战按钮，然后截屏游戏窗口，通过OpenCV查找小图（比如挑战按钮），如果查找到了就进行点击操作。可以看下这个方法的实现,199行的`Demo()`[点击跳转](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/Function/Function.Other.cs)
> > > > > > Java和C#差不太多，上手还是比较容易的。百度百度就差不多了
> > > > > 
> > > > > 
> > > > > 好的 多谢大佬指点，今晚把环境搭建起来了，核心逻辑确实基本能看懂，之后得空了我尝试下加入我的想法
> > > > 
> > > > 
> > > > 嗯嗯，届时欢迎提交pull request，加油！！！（最近懒得玩，也懒得写了）
> > > 
> > > 
> > > 昨天游戏更新了,我尝试把契灵探查功能和017的50自选加进去了,现在想实现自动捕捉契灵的功能,中间有一个步骤要求发指令控制鼠标在屏幕画条折现连接三个点,这个控制鼠标绘图的功能我该用什么关键字百度呢
> > 
> > 
> > win32API实现鼠标点击 win32API实现鼠标移动 MOUSE_MOVE ，对应的具体事件名忘记了。
> > 我使用的win32api的包是 PInvoke.NET
> 
> 回头搞好了合并出来 ![162B2D37](https://user-images.githubusercontent.com/131952790/244636760-508253d3-0118-4bcd-9648-9962d6277e5f.png) 我已经好多天没上线了 ![162B68F7](https://user-images.githubusercontent.com/131952790/244636814-3bdb2800-7f54-4e73-9c72-553e5ac4ea7d.png)

嗯嗯没事大佬,我这边目前能自给自足了,mumu模拟器的问题排查发现应该是mumu模拟器挑战按钮的图片素质跟resources里面的不太一致没有匹配上,我又在mumu模拟器上截了一个加入到打手循环里的挑战_组队3.png来识别就兼容mumu和雷电了,目前的想法是清突破的逻辑应该可以优化高效一点,不过这几天要出差了 pull request估计要过段时间(赶着devexpress的30天试用期前)

**Comment by BaryRR** [comment]
> > > > > > > > 好的,有时间我测试一下，用mumu以来我还没组过队
> > > > > > > 
> > > > > > > 
> > > > > > > 好的 麻烦大佬了,话说我本身是java的后端开发,可以透露一下这个项目的实现思想是什么嘛,这两天使用下来我也有些优化的想法想自己尝试一下,但是我又没学过C#还建议尝试吗
> > > > > > 
> > > > > > 
> > > > > > 大致思路就是截取游戏里面的局部图片，比如挑战按钮，然后截屏游戏窗口，通过OpenCV查找小图（比如挑战按钮），如果查找到了就进行点击操作。可以看下这个方法的实现,199行的`Demo()`[点击跳转](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/Function/Function.Other.cs)
> > > > > > Java和C#差不太多，上手还是比较容易的。百度百度就差不多了
> > > > > 
> > > > > 
> > > > > 好的 多谢大佬指点，今晚把环境搭建起来了，核心逻辑确实基本能看懂，之后得空了我尝试下加入我的想法
> > > > 
> > > > 
> > > > 嗯嗯，届时欢迎提交pull request，加油！！！（最近懒得玩，也懒得写了）
> > > 
> > > 
> > > 昨天游戏更新了,我尝试把契灵探查功能和017的50自选加进去了,现在想实现自动捕捉契灵的功能,中间有一个步骤要求发指令控制鼠标在屏幕画条折现连接三个点,这个控制鼠标绘图的功能我该用什么关键字百度呢
> > 
> > 
> > win32API实现鼠标点击 win32API实现鼠标移动 MOUSE_MOVE ，对应的具体事件名忘记了。
> > 我使用的win32api的包是 PInvoke.NET
> 
> 回头搞好了合并出来 ![162B2D37](https://user-images.githubusercontent.com/131952790/244636760-508253d3-0118-4bcd-9648-9962d6277e5f.png) 我已经好多天没上线了 ![162B68F7](https://user-images.githubusercontent.com/131952790/244636814-3bdb2800-7f54-4e73-9c72-553e5ac4ea7d.png)

嗯嗯没事大佬,我这边目前能自给自足了,mumu模拟器的问题排查发现应该是mumu模拟器挑战按钮的图片素质跟resources里面的不太一致没有匹配上,我又在mumu模拟器上截了一个加入到打手循环里的挑战_组队3.png来识别就兼容mumu和雷电了,目前的想法是清突破的逻辑应该可以优化高效一点,不过这几天要出差了 pull request估计要过段时间(赶着devexpress的30天试用期前)

**Comment by BaryRR** [comment]
> Owner
明白了 配合BUTTONDOWN，MOUSEMOVE和LBUTTONUP就可以实现简单的鼠标绘图事件，但是MOUSEMOVE事件感觉很容易被检测出来时脚本吧

**Comment by YaKun9** [comment]
> 

嗯，突破是整个里面最烦人的模块了，一个屏幕上好多图片同时存在。改改流程好一些，现在的流程没有优化的必要，建议直接重构

**Comment by YaKun9** [comment]
> 

是的，所以可以做一下仿真处理
