### ISSUE TITLE
新手请教

### ISSUE THREAD

**Issue by li9296** [YaKun9/YYS-AutoHelpMe#9]
很感谢大佬写的脚本，让我受益良多
这里就是想请教一下，如何在release的打包版本里调整全局的两次点击的间隔和随机延迟......
再次感谢大佬！！！

**Comment by YaKun9** [comment]
li9296
        您好！我已收到您的邮件。
        


        无法在release打包好的文件里调整,因为是写死的。你可以自己改了构建一下


2023-9-11
| |
劉亞坤
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年9月11日 22:25 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [YaKun9/YYS-AutoHelpMe] 新手请教 (Issue #9) |

很感谢大佬写的脚本，让我受益良多
这里就是想请教一下，如何在release的打包版本里调整全局的两次点击的间隔和随机延迟......
再次感谢大佬！！！

**Comment by li9296** [comment]
谢谢大佬的回复！
我先尝试一下！

**Comment by YaKun9** [comment]
> 谢谢大佬的回复！ 我先尝试一下！

在[WinHelper.cs](https://github.com/YaKun9/YYS-AutoHelpMe/blob/main/AutoHelpMe/WinHelper.cs)文件中，第277行，`Click`方法，查找对应的引用即可

**Comment by li9296** [comment]
谢谢大佬的帮助，在这里找到了随机坐标和随即延迟！
